export const TEAM_LABELS = {
  villager: 'Dân làng',
  werewolf: 'Ma sói',
  vampire: 'Ma cà rồng',
  tanner: 'Người thuộc da',
  cultist: 'Tà giáo',
  arsonist: 'Kẻ phóng hỏa',
};

export const PHASE_LABELS = {
  lobby: 'Lobby',
  night_intro: 'Bắt đầu đêm',
  night: 'Đêm',
  night_results: 'Sáng',
  day_discuss: 'Bàn luận',
  day_vote: 'Vote',
  day_results: 'Kết quả vote',
  ended: 'Kết thúc',
};

export const ROLE_META = {
  villager: { name: 'Dân làng', emoji: '👨‍🌾', icon: '🌾', color: '#22c55e' },
  seer: { name: 'Tiên tri', emoji: '🔮', icon: '🌙', color: '#a855f7' },
  witch: { name: 'Phù thủy', emoji: '🧙‍♀️', icon: '⚗️', color: '#7c3aed' },
  guard: { name: 'Bảo vệ', emoji: '🛡️', icon: '✨', color: '#3b82f6' },
  hunter: { name: 'Thợ săn', emoji: '🏹', icon: '🎯', color: '#dc2626' },
  cupid: { name: 'Thần tình yêu', emoji: '💘', icon: '❤️', color: '#ec4899' },
  priest: { name: 'Linh mục', emoji: '⛪', icon: '✨', color: '#fbbf24' },
  mason: { name: 'Người xây', emoji: '🔨', icon: '🏛️', color: '#a16207' },
  detective: { name: 'Thám tử', emoji: '🕵️', icon: '🔍', color: '#0891b2' },
  troubadour: { name: 'Nhạc sĩ', emoji: '🎭', icon: '🎵', color: '#10b981' },
  spellcaster: { name: 'Pháp sư', emoji: '✨', icon: '🌟', color: '#8b5cf6' },
  werewolf: { name: 'Ma sói', emoji: '🐺', icon: '🌕', color: '#dc2626' },
  alpha_wolf: { name: 'Sói đầu đàn', emoji: '🐺', icon: '👑', color: '#991b1b' },
  wolf_cub: { name: 'Sói con', emoji: '🐺', icon: '🐶', color: '#b91c1c' },
  lone_wolf: { name: 'Sói cô độc', emoji: '🐺', icon: '🌑', color: '#7f1d1d' },
  vampire: { name: 'Ma cà rồng', emoji: '🧛', icon: '🦇', color: '#7c2d12' },
  tanner: { name: 'Người thuộc da', emoji: '🎭', icon: '🪓', color: '#f59e0b' },
  cultist: { name: 'Tà giáo', emoji: '👤', icon: '🌚', color: '#9333ea' },
  arsonist: { name: 'Kẻ phóng hỏa', emoji: '🔥', icon: '🕯️', color: '#ea580c' },
};

export const ROLE_DESC = {
  villager: 'Không có khả năng đặc biệt. Tìm và loại trừ ma sói qua bỏ phiếu ban ngày.',
  seer: 'Mỗi đêm, được điều tra một người để biết họ là phe Dân hay Ma sói.',
  witch: 'Có 1 bình cứu (cứu người bị giết) và 1 bình độc (giết 1 người). Mỗi bình dùng 1 lần.',
  guard: 'Mỗi đêm bảo vệ 1 người. Không thể bảo vệ cùng 1 người 2 đêm liên tiếp.',
  hunter: 'Khi bị giết (cả đêm lẫn ngày), được bắn chết 1 người cùng lúc.',
  cupid: 'Đêm đầu, ghép 2 người thành cặp tình nhân. Nếu 1 chết, 2 kia cũng chết theo.',
  priest: 'Mỗi đêm có thể phong ấm 1 người để chống lại sự chuyển hóa (Cult, Vampire).',
  mason: 'Biết ai là Mason khác. Nếu chỉ có 1 Mason thì không có khả năng đặc biệt.',
  detective: 'Mỗi đêm điều tra 1 người. Nếu trúng sói, được điều tra thêm 1 người.',
  troubadour: 'Nếu chỉ còn 1 Troubadour sống, thắng.',
  spellcaster: 'Mỗi đêm, có thể phong ấm 1 người hoặc xóa phong ấm của 1 người.',
  werewolf: 'Mỗi đêm, cùng đồng đội chọn 1 người để giết.',
  alpha_wolf: 'Sói đặc biệt, mỗi đêm có thể cắn 1 người.',
  wolf_cub: 'Khi chết, đêm tiếp theo sói được giết 2 người thay vì 1.',
  lone_wolf: 'Khi là sói duy nhất còn sống, giết được 2 người mỗi đêm.',
  vampire: 'Giống Ma sói nhưng thuộc phe riêng.',
  tanner: 'Thắng nếu bị dân làng treo cổ vào ban ngày.',
  cultist: 'Mỗi đêm có thể chuyển hóa 1 người thành Cultist.',
  arsonist: 'Mỗi đêm tẩm dầu 1 người. Có thể đốt tất cả người đã tẩm dầu.',
};